### ISSUE TITLE
Error when using dumpSTR

### ISSUE THREAD

**Issue by gspirito** [gymreklab/GangSTR#75]
Hello, I installed GangSTR, dumpSTR and the related dependancies and i run into an error when using dumpSTR to filter a vcf file obtained with GangSTR:

# GangSTR command
GangSTR --bam <bam list> --ref /path/ucsc.hg19.fasta --regions hg19_ver13.bed --out ASD 

# dumpSTR command
dumpSTR --filter-spanbound-only --filter-badCI --max-call-DP 2000 --min-call-DP 15 --filter-regions /path/filter_files/hg19_segmentalduplications.bed.gz --vcf ASD.vcf --out ASD_filtered

# Error
Traceback (most recent call last):
  File "/usr/local/bin/dumpSTR", line 9, in <module>
    load_entry_point('strtools==1.0.0', 'console_scripts', 'dumpSTR')()
  File "/usr/local/lib/python3.5/dist-packages/strtools-1.0.0-py3.5.egg/dumpSTR/dumpSTR.py", line 383, in main
  File "/usr/local/lib/python3.5/dist-packages/strtools-1.0.0-py3.5.egg/dumpSTR/filters.py", line 86, in __call__
  File "/usr/local/lib/python3.5/dist-packages/strtools-1.0.0-py3.5.egg/strtools/utils/utils.py", line 29, in GetHomopolymerRun
ValueError: max() arg is an empty sequence

I was wondering what could be the cause for this.

Thank you in advance.

**Comment by nmmsv** [comment]
hello,
we fixed some version issues recently in dumpSTR, and that may have fixed this problem. Can you please try again with the latest version of dumpSTR? If the issue persists, please don't hesitate to submit an issue in the STRTools repository, that way we can get to it faster.
https://github.com/gymreklab/STRTools/issues

Thanks.
